/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
    // Deletes ALL existing entries
    await knex('species').del()
    await knex('species').insert([
      {
      id: 1,
      scientific_name: 'Monstera Deliciosa',
      common_name: 'Swiss Cheese Plant',
      category: 'Temperate',
      description: 'Member of the arum family Araceae, Monstera is native to tropical forests of southern Mexico, south to Panama. As houseplants, they are very unique, easygoing and always eyecatching because of their dramatic green leaves. They are vining plants and love to trail over the pot or climb along a trellis.',
      photo: 'https://as2.ftcdn.net/v2/jpg/02/12/89/91/1000_F_212899169_gON1sUOS7fpB8sjjtZvWhVdoHRZpNo2u.jpg',
      light_level: 'Bright, indirect light',
      soil_type: 'Dense, nutrient-rich soil',
      toxic: true,
      difficulty_level: 'Easy',
      watering_interval: 14,
    }, 
      {
      id: 2,
      scientific_name: 'Orchidaceae',
      common_name: 'Orchid',
      category: 'Temperate',
      description: 'The orchid family is a diverse and widespread family of lowering plants, with blooms that are often colourful and fragrant. They are native to Southern China, Taiwan , Southeast Asia and New Guinea. They are very low-maintenance and can stay in bloom for up to four months if cared for properly.',
      photo: 'https://assets.eflorist.com/assets/products/PHR_/TPL05-1A.jpg',
      light_level: 'Indirect bright light',
      soil_type: 'Orchid potting mix',
      toxic: false,
      difficulty_level: 'Intermediate',
      watering_interval: 14,
    },
      {
      id: 3,
      scientific_name: 'Cactaceae',
      common_name: 'Cactus',
      category: 'Desert',
      description: 'Native to the Americas, cactui can be found ranging from Patagonia to some parts of Western Canada. They have adapted to live in extremely dry environments. As a result, they require very minimal care and and go a long time between waterings.',
      photo: 'https://i.pinimg.com/736x/ee/ab/65/eeab65d75ae553b503f2c6a61154c0fc--indoor-house-plants-indoor-gardening.jpg',
      light_level: 'Bright, direct sunlight',
      soil_type: 'Cactus growing mix',
      toxic: false,
      difficulty_level: 'Intermediate',
      watering_interval: 14,
    },
      {
      id: 4,
      scientific_name: 'Ficus lyrata',
      common_name: 'Fiddle Leaf Fig',
      category: 'Tropical',
      description: 'Native to western Africa, as a houseplant, it is a bit tricky to care. It does not respond well to being moved if it is in a spot where it is thriving. Being a tropical plant, it does not do well to cold temperatures, but has been known to survive temperatures down to 10°C.',
      photo: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSkopIl_R0u0R0tFA6_2joPTCXB_TBVX4IY0Fuz3RamMzAMAZa1ia6wG5MfBWegjUk5nkHDpdSuQGs7tw3wL3ukfPWILprZ9gfZMqpJBj1AnoRSJj3WF1OrFA&usqp=CAE',
      light_level: 'Indirect bright light',
      soil_type: 'A well draining high in organic matter',
      toxic: true,
      difficulty_level: 'Intermediate',
      watering_interval: 10,
    },
      {
      id: 5,
      scientific_name: 'Hoya',
      common_name: 'Hoya',
      category: 'Tropical',
      description: 'Native to several countries in Asia, Hoyas are slow-growing, vining plants. They are known as wax plants due to their thick and shiny foliage. They are very popular houseplants due to their low maintanence.',
      photo: 'https://cdn.shopify.com/s/files/1/1938/3931/files/Hoya_AdobeStock_862454_square.png?v=1559070163',
      light_level: 'Indirect bright light',
      soil_type: 'Dense, nutrient-rich soil',
      toxic: false,
      difficulty_level: 'Intermediate',
      watering_interval: 7,
    },
      {
      id: 6,
      scientific_name: 'Calathea Obtusifolia',
      common_name: 'Calathea',
      category: 'Tropical',
      description: 'Calatheas are known for their bold patterned foliage. The leaves of most Calathea varieties fold up slightly during the night time, revealing the often colourful undersides of their striking leaves. Because of their tendancy to fold up, they are often referred to as "prayer plants.',
      photo: 'https://pyxis.nymag.com/v1/imgs/284/267/87ccd2e3f999b864b0b1bab008267cca92-calathea.2x.rsquare.w600.jpg',
      light_level: 'Bright indirect sunlight',
      soil_type: '50% potting soil, 20% orchid bard, 20% charcoal and 10% perlite',
      toxic: false,
      difficulty_level: 'Hard',
      watering_interval: 14,
    },
      {
      id: 7,
      scientific_name: 'Kalanchoe',
      common_name: `Widow's Thrill`,
      category: 'Temperate',
      description: `Native to tropical Africa, this hardy plant is a popular houseplant because of it's low maintanence. Often only needing few waterings, this plant will usually flower year round if cared for properly`,
      photo: 'https://img.teleflora.com/images/o_0/l_flowers:T91-2A,pg_6/w_368,h_460,cs_no_cmyk,c_pad/f_jpg,q_auto:eco,e_sharpen:200/flowers/T91-2A/BountifulKalanchoe',
      light_level: 'Bright direct sunlight',
      soil_type: 'Soil 60% peat moss and 40% perlite',
      toxic: true,
      difficulty_level: 'Easy',
      watering_interval: 21,
    },
    ]);
};
